name: jenosize
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  google_maps_flutter: ^2.2.5
  google_place: ^0.4.7
  dio: ^5.1.1
  auto_size_text: ^3.0.0
  uuid: ^3.0.7
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/